### ISSUE TITLE
install error,python version?

### ISSUE THREAD

**Issue by zhangzscn** [3D-FRONT-FUTURE/NeuDA#2]
What version of python do you use?

pip install -r requirements.txt
Collecting imageio==2.15.0 (from -r requirements.txt (line 1))
  Using cached imageio-2.15.0-py3-none-any.whl (3.3 MB)
Collecting matplotlib==3.3.4 (from -r requirements.txt (line 2))
  Using cached matplotlib-3.3.4-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
Collecting numpy==1.19.2 (from -r requirements.txt (line 3))
  Using cached numpy-1.19.2-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting torch==1.8.0 (from -r requirements.txt (line 4))
  Using cached torch-1.8.0-cp38-cp38-manylinux1_x86_64.whl (735.5 MB)
Collecting torchvision==0.9.0 (from -r requirements.txt (line 5))
  Using cached torchvision-0.9.0-cp38-cp38-manylinux1_x86_64.whl (17.3 MB)
ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement pytorch3d==0.6.1 (from versions: 0.1.1, 0.2.0, 0.2.5, 0.3.0)
ERROR: No matching distribution found for pytorch3d==0.6.1

**Comment by BwCai** [comment]
Sorry for the late reply. This repo was tested in python 3.6.13, please try it again.
